name: deploy image function to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          cd lambda/image
          npm install
          npm run build --if-present
        env:
          CI: true

      - name: Install zip
        uses: montudor/action-zip@v0.1.1

      - name: Zip output
        run: zip -qq -r bundle.zip ./
        working-directory: ./lambda/image
      # - name: zip
      #   uses: montudor/action-zip@v0.1.0
      #   with:
      #     args: zip -qq -r ./bundle.zip ./

      - name: Deploy lambda
        run: |
          aws lambda update-function-code --function-name "gmail-read-recipt" --zip-file "fileb://lambda/image/bundle.zip" 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1

      # - name: default deploy
      #   uses: appleboy/lambda-action@master
      #   with:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: us-east-2
      #     function_name: gmail-read-receipt
      #     zip_file: ./lambda/image/bundle.zip
      #     timeout: 10